version: "3.8"

services:
  # 1. Database (PostgreSQL 16 + PGroonga)
  db:
    image: groonga/pgroonga:3.1.7-alpine-16
    container_name: sfms-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      TZ: Asia/Seoul
    ports:
      - "5432:5432"  # WSL에서 localhost:5432로 접근 가능
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
      - ./pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sfms-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Cache & Session Store (Redis)
  redis:
    image: redis:7-alpine
    container_name: sfms-redis
    restart: always
    ports:
      - "6379:6379"  # WSL에서 localhost:6379로 접근 가능
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-password123!}
    volumes:
      - ./data/redis:/data
    networks:
      - sfms-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-password123!}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Object Storage (MinIO)
  minio:
    image: minio/minio:latest
    container_name: sfms-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "9000:9000"  # S3 API 포트 (localhost:9000)
      - "9001:9001"  # 관리자 웹 콘솔 (localhost:9001)
    volumes:
      - ./data/minio:/data
    networks:
      - sfms-net

  # 4. Database Admin (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: sfms-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "5050:80"    # 웹 브라우저 접속용 (localhost:5050)
    volumes:
      - ./data/pgadm:/var/lib/pgadmin
    networks:
      - sfms-net

  # 5. Offline Version Control (Gitea)
  gitea:
    image: gitea/gitea:latest
    container_name: sfms-gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - HOST=db:5432
      - NAME=${DB_NAME}
      - USER=${DB_USER}
      - PASSWD=${GITEA_DB_PASSWORD}
    ports:
      - "3000:3000"  # Gitea 웹 UI (localhost:3000)
      - "222:22"
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sfms-net

  # 6. Container Management (Portainer)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: sfms-portainer
    restart: always
    ports:
      - "9002:9000"  # Portainer 웹 UI (localhost:9002)
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      - sfms-net

networks:
  sfms-net:
    driver: bridge