# 1단계: 빌드 스테이지 (Build Stage)
FROM docker.io/library/node:24-slim AS build-stage
WORKDIR /app

# pnpm 설치 및 의존성 복사
# RUN npm install -g pnpm\
#   # 프로젝트 루트를 기준으로 frontend 폴더의 의존성 복사
#   COPY frontend/package.json frontend/pnpm-lock.yaml* ./
# RUN pnpm install --frozen-lockfile
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install

# 소스 코드 복사 및 빌드 실행
# COPY . .
# RUN pnpm run build
COPY . .
RUN pnpm build


# 2단계: 실행 스테이지 (Production Stage)
# 빌드된 결과물만 가벼운 nginx로 옮겨서 보안과 용량을 모두 잡습니다.
FROM docker.io/library/nginx:stable-alpine
WORKDIR /usr/share/nginx/html

# 1단계에서 빌드된 dist 폴더 내용만 복사
# 빌드된 결과물을 Nginx 기본 경로로 복사
# COPY --from=build-stage /app/dist /usr/share/nginx/html

# # 설정 및 래퍼 스크립트 복사
# COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
# COPY ./nginx/scripts/entrypoint-wrapper.sh /usr/local/bin/

# RUN chmod +x /usr/local/bin/entrypoint-wrapper.sh

# ENTRYPOINT ["/usr/local/bin/entrypoint-wrapper.sh"]
# 빌드된 정적 파일 복사
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Nginx 설정 파일 복사
COPY ./infra/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
