services:
  # 1. 프론트엔드 빌더 서비스
  frontend:
    profiles: ["build"]
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-builder
    command: ["pnpm", "build"]
    volumes:
      - ../frontend:/app:Z
      - ../frontend/dist:/app/dist:Z
    networks:
      - sfms-net

  # 2. Nginx 서비스
  nginx:
    image: docker.io/library/nginx:stable-alpine
    container_name: nginx
    depends_on:
      api:
        condition: service_healthy
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/scripts/entrypoint-wrapper.sh:/usr/local/bin/entrypoint-wrapper.sh:ro
      - ./data/logs/nginx:/var/log/nginx:Z
      - ../frontend/dist:/usr/share/nginx/html:ro,Z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/entrypoint-wrapper.sh"]
    networks:
      - sfms-net
